Parameters:
  EnvironmentName:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Stage
      - Prod
  ServiceNameDashy:
    Type: String
    Default: links-air
Mappings:
  Settings:
    EnvironmentNameLower:
      Dev: dev
      Stage: stage
      Prod: prod
Resources:
  EnvironmentSecrets:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: !Sub Secrets that get put into the environment for the ${ServiceNameDashy} ecs containers
      Name: !Join ['', [!FindInMap [Settings, EnvironmentNameLower, !Ref EnvironmentName], '-', !Ref ServiceNameDashy]]
      SecretString: '{}'

Outputs:
  EnvironmentSecrets:
    Value: !Ref EnvironmentSecrets
    Export:
      Name: !Sub "${AWS::StackName}-EnvironmentSecrets"